server:
  port: 40001

#dubbo
dubbo:
  scan:
    base-packages: com.xsw.gateway.rpc
  application:
    name: xsw-gateway
  cloud:
    subscribed-services: xsw-auth,xsw-blog

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      # 配置路由规则
      routes:
        - id: xsw-auth          #我们自定义的路由 ID，保持唯一
          ## 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
          uri: lb://xsw-auth
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # 路径匹配，以 auth 开头，直接配置是不生效的，看 filters 配置
            - Path=/auth/**
          filters:
            # 前缀过滤，默认配置下，我们的请求路径是 http://localhost:8888/business-oauth2/** 这时会路由到指定的服务
            # 此处配置去掉 1 个路径前缀，再配置上面的 Path=/api/**，就能按照 http://localhost:8888/api/** 的方式访问了
            - StripPrefix=1
        - id: xsw-blog
          uri: lb://xsw-blog
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=0